apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-service
  name: go-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-service
    spec:
      containers:
      - image: wxwmatt/go-service:1.0
        name: go-service
        resources: {}
        env:
        - name: MY_APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: MY_APP_VERSION
          value: '1.1'
        - name: MY_APP_GROUP
          value: 'my_group'
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
status: {}
